### ISSUE TITLE
Issue with 3D secure card

### ISSUE THREAD

**Issue by parasdaff** [stripe/stripe-connect-rocketrides#12]
Hi,
I am facing some issue while requesting ride using 3d secure card.

![simulator screen shot - iphone 8 - 2017-12-11 at 16 49 03](https://user-images.githubusercontent.com/20792433/33830656-04b8d5be-de9b-11e7-9a60-5e3695424497.png)

**Comment by romain-stripe** [comment]
Hi @parasdaff, thanks so much for surfacing this issue and apologies for the delay!

You're right, I haven't tried this iOS app with a card that requires 3D Secure. I assume you were trying this in test mode using the card number that we recommend on [testing](https://stripe.com/docs/testing#3ds-cards)? I'll try to reproduce and see how we can fix this. Thanks!

**Comment by trag-stripe** [comment]
Closing issue - will combine with other related asks. Thx
