### ISSUE TITLE
Not taken back into Rocketrides after Authing in with Stripe

### ISSUE THREAD

**Issue by spitza** [stripe/stripe-connect-rocketrides#16]
While signing in to become a pilot and logging in with my Stripe credentials, I went through the forgot password flow. After doing that and completing signup, I wasn't redirected back to rocketrides.io, but instead was dropped into the Stripe dashboard. Is this intentional, and is it the intended flow for Stripe Connect in general? Is this a result of going through the forgot password flow?

**Comment by mglukhovsky** [comment]
@spitza: As @JBader89 mentioned, you'll need to make sure you provide the specific redirect URI in the Stripe Dashboard under your [Connect settings](https://dashboard.stripe.com/account/applications/settings). Express will _only_ allow you to redirect to URIs that you've explicitly enabled for your account (for security reasons).

You can include multiple URIs, which can be useful for testing on `localhost`. You can then specify which you'd like to use with the [`redirect_uri` OAuth parameter](https://stripe.com/docs/connect/oauth-reference#redirect-uri) when you initiate the Express flow.

**Comment by spitza** [comment]
Got it, thanks @mglukhovsky and @JBader89!
