### ISSUE TITLE
Error adding token to customer: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by ArtSebus** [stripe/stripe-connect-rocketrides#17]
I am unable to book a ride on a localhost server. following error is shown from the server for account without bank account linked: 

```
Error adding token to customer: Cannot read property 'id' of null
```
I think this is corresponding log from stripe

```
{
  "error": {
    "code": "parameter_missing",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-missing",
    "message": "Missing required param: destination[account].",
    "param": "destination[account]",
    "type": "invalid_request_error"
  }
}
```

Judging by the log file, it seems that it's not related to un verified rider. 

ps. thanks a lot to the team & Romain for this helpful work to get us started.

**Comment by paddlefish** [comment]
I'm getting the same error.  How did you work around it?

**Comment by Henry-** [comment]
Same here. Please help

**Comment by Henry-** [comment]
The error was that there is no pilot being selected for the ride. So then there is not ID passed to the stripe payment  in the rides.js file: 

`    const charge = await stripe.charges.create({
      source: source,
      amount: ride.amount,
      currency: ride.currency,
      customer: passenger.stripeCustomerId,
      description: config.appName,
      statement_descriptor: config.appName,
      destination: {
        // Send the amount for the pilot after collecting 20% platform fees.
        // Typically, the `amountForPilot` method simply computes `ride.amount * 0.8`.
        amount: ride.amountForPilot(),
        // The destination of this charge is the pilot's Stripe account.
        account: pilot.stripeAccountId **THIS IS SENT AS NIL**
      }
    });`

**Comment by mg-stripe** [comment]
This should be fixed in the latest release. If you run into it again, please let us know and we can reopen this issue!
