### ISSUE TITLE
In app onboarding

### ISSUE THREAD

**Issue by Gior80** [stripe/stripe-connect-rocketrides#20]
I'm using firebase Backend. is there a guide on how to: 

deploy webapp  to firebase
make IN APP on boarding (I think via uiwebview ? )

**Comment by mg-stripe** [comment]
Hey there, we don't yet have a Firebase and Stripe guide, however, you may want to check out [this guide from the Firebase team](https://firebase.google.com/docs/use-cases/payments) which walks through how to build with Stripe on their platform.
