### ISSUE TITLE
Invalid Stripe API version: 2018-11-21 accounts_upgrade=true

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-connect-rocketrides#22]
Tried the express account on boarding process today and this is the error I'm seeing on rocketrides.io:

<img width="492" alt="screen shot 2019-02-20 at 5 08 23 pm" src="https://user-images.githubusercontent.com/127062/53137299-07180980-3537-11e9-8b20-32e5ba0c3ad1.png">

**Comment by mglukhovsky** [comment]
Hey there, we're looking into this now! Thanks for reporting it.

**Comment by mglukhovsky** [comment]
This should be resolved. 👍
