### ISSUE TITLE
The app is broken

### ISSUE THREAD

**Issue by kevflynn** [stripe/stripe-connect-rocketrides#26]
Tried logging in
Internal server error

**Comment by mg-stripe** [comment]
@kevflynn: Are you experiencing this on localhost, or on rocketrides.io? Do you have an existing account, or was this for a new account?

**Comment by scottybe** [comment]
I have the same problem. As soon as I login at rocketrides.io, I see "Internal Server Error" in the top right corner.

**Comment by mglukhovsky** [comment]
We've isolated the problem to an issue with the deployment environment and its database connection, so we're deploying a full database cluster. The app is back up, but will have intermittent issues until the cluster is up and running: I'll post an update here when it's ready.

**Comment by mg-stripe** [comment]
I've rewritten the database connection code, but we're still investigating some connectivity issues. I'll close this issue for now, but feel free to reopen if you run into an issue again.
