### ISSUE TITLE
This email already exists. Please try to log in instead.

### ISSUE THREAD

**Issue by iamsayantan** [stripe/stripe-connect-rocketrides#28]
Getting email already exists error while trying to sign up. And if I try to login with the email and some random password getting internal server error.
![Screenshot from 2019-05-27 18-02-19](https://user-images.githubusercontent.com/19422764/58420113-20869f80-80aa-11e9-89f3-1d86bb565d68.png)
![Screenshot from 2019-05-27 18-03-03](https://user-images.githubusercontent.com/19422764/58420261-6f343980-80aa-11e9-82c5-c4ed99a7f5f3.png)

**Comment by mg-stripe** [comment]
This is related to #28; I've rewritten the database connection code which (hopefully) should resolve this.
