### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by themakshter** [stripe/stripe-connect-rocketrides#36]
I was testing this application and stupidly linked it to my email which had other accounts. Once I closed all the other accounts, I cannot re-create a stripe account or log into it because I believe this application created a stripe account for me. Could this be removed or checked?

**Comment by trag-stripe** [comment]
Please contact support.stripe.com to look up your account. If you can log into your account, follow these steps: https://support.stripe.com/questions/close-a-stripe-account
