### ISSUE TITLE
Please add a react example

### ISSUE THREAD

**Issue by bionicles** [stripe/stripe-connect-rocketrides#39]
I'd like to put Connect on a react app but there's no example. The only example is for a swift app

Would it please be possible to add a usage example of a react stripe connect app?

Then it would be much easier to develop web platform marketplace type things...

**Comment by valiaghaei** [comment]
how  we  can add  this  to  react  native  app ? i can't  find  any  sources  to  use it in react native

**Comment by hstandeffer** [comment]
Any update on this? I am trying to implement this on my MERN app, but am having trouble integrating my authentication method into the Stripe redirect back to my site

**Comment by trag-stripe** [comment]
Hello! Please let us know what you need in a React Native sample using this interest form: https://app.smartsheet.com/b/form/b1a1053eaac7496eb0ae7892ebd68973 Thanks!
