### ISSUE TITLE
how we  can  implement this  in  react  native  ?

### ISSUE THREAD

**Issue by valiaghaei** [stripe/stripe-connect-rocketrides#41]
i studied all sources in the stripe sites , but i can't understand how we can implement this in react native , like below link access to dashboard by entering  stripe account and password.
https://rocketrides.io/

**Comment by trag-stripe** [comment]
Hello - please let us know if you're still interested in a Stripe React Native sample but filling out this interest form: https://app.smartsheet.com/b/form/b1a1053eaac7496eb0ae7892ebd68973 Thanks!
